spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql-db}:3306/locationsearchsvc?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:appuser}
    password: ${MYSQL_PASSWORD:appuser}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
