spring:
  datasource:
    url: ${MYSQL_HOST:jdbc:mysql://127.0.0.1:3306/locationsearchsvc?autoReconnect=true&useSSL=false}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:appuser}
    password: ${MYSQL_PASSWORD:appuser}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
