spring:
  datasource:
    url: ${MYSQL_HOST:jdbc:mysql://127.0.0.1:3306/locationsearchsvc?autoReconnect=true&useSSL=false}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:appuser}
    password: ${MYSQL_PASSWORD:appuser}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

logging:
  level:
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG

rabbitmq:
  queue: location-queue
  exchange: location-exchange
  routing-key: location.routing
