spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql-db}:3306/locationsearchsvc?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:appuser}
    password: ${MYSQL_PASSWORD:appuser}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

logging:
  level:
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG

rabbitmq:
  queue: location-queue
  exchange: location-exchange
  routing-key: location.routing
